name: 'Composite test'
description: 'Composite tests.'
inputs:
  test-param:  
    description: 'Test param'
    required: true
    default: 'this is a test param'
  
runs:
  using: "composite"
  steps:
    - id: automation-script
      run: |
        ls -la
        pwd
        cat readme.md
        echo "The test param says: ${{ inputs.test-param }}"
      shell: bash