name: 'Composite test'
description: 'Composite tests.'
inputs:
  test-param:  
    description: 'Test param'
    required: true
    default: 'this is a test param'
  
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - id: automation-script
      run: |
        ls -la
        pwd
        cat ./README.md
        echo "The test param says: ${{ inputs.test-param }}"
        python -m venv venv
        source venv/bin/activate
        ls -la
        pwd
        pip install -r ./requirements.txt
        python test.py        
      shell: bash